export default {
  autoComplete: require('./autoComplete').default,
  button: require('./button').default,
  cascader: require('./cascader').default,
  checkbox: require('./checkbox').default,
  datePicker: require('./datePicker').default,
  // formButton: require('./formButton').default,
  grid: require('./grid').default,
  input: require('./input').default,
  inputNumber: require('./inputNumber').default,
  radio: require('./radio').default,
  rate: require('./rate').default,
  select: require('./select').default,
  slider: require('./slider').default,
  table: require('./table').default,
  switch: require('./switch').default,
  textarea: require('./textarea').default,
  timePicker: require('./timePicker').default,
  upload: require('./upload').default,
  line: require('./line').default
}
